srcType: Amazon_S3
srcBucketName: src-bucket
srcBucketPrefix:
srcRegion: us-west-2
srcCredential: src
SrcInCurrentAccount: false

destBucketName: dest-bucket
destBucketPrefix:
destRegion: cn-north-1
destCredential:
destStorageClass: STANDARD
destInCurrentAccount: true

jobTableName: test-table
jobQueueName: test-queue

options:
  chunkSize: 5
  multipartThreshold: 10
  maxKeys: 1000
  messageBatchSize: 10
  finderDepth: 0
  finderNumber: 1
  workerNumber: 4
